version: '3'

services:
  datahog:
    build:
      context: .
      dockerfile: dockerfile-datahog
    volumes:
      - ./datahog:/app
      - /app/node_modules
  redis:
    image: "redis:alpine"
    command: redis-server
  techtest-api: 
    build:
      context: .
      dockerfile: dockerfile-techtest
    depends_on: 
      - "redis"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run api
    links:
      - "redis"
      - "datahog"
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROVIDER_GAS_URL=http://datahog:3000/providers/gas
      - PROVIDER_INTERNET_URL=http://datahog:3000/providers/internet
  techtest-worker:
    build:
      context: .
      dockerfile: dockerfile-techtest
    depends_on: 
      - "redis"
    links:
      - "redis"
      - "datahog"
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run worker